media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "poems"
    label: "कविताएँ / Poems"
    folder: "content/poems"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "शीर्षक / Title", name: "title", widget: "string" }
      - { label: "कवि / Poet", name: "poet", widget: "string" }
      - label: "विषय / Themes"
        name: "themes"
        widget: "list"
        hint: "Add themes one by one (e.g. भक्ति, श्रृंगार, प्रकृति)"
      - label: "पाठ लिंक / Audio URL (Archive.org embed link)"
        name: "audio_url"
        widget: "string"
        required: false
        hint: "Paste the Archive.org embed URL here"
      - label: "टिप्पणी / Notes"
        name: "notes"
        widget: "text"
        required: false
      - label: "कविता / Poem Text"
        name: "body"
        widget: "markdown"
      - { label: "प्रकाशित / Published", name: "draft", widget: "boolean", default: false, hint: "Turn ON to hide from site" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "poets"
    label: "कवि / Poets"
    folder: "content/poets"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "नाम / Name", name: "title", widget: "string" }
      - { label: "काल / Dates", name: "dates", widget: "string", required: false, hint: "e.g. 1478–1583" }
      - { label: "क्षेत्र / Region", name: "region", widget: "string", required: false }
      - label: "चित्र / Photo"
        name: "image"
        widget: "image"
        required: false
      - label: "जीवन परिचय / Biography"
        name: "body"
        widget: "markdown"
      - { label: "Date", name: "date", widget: "datetime" }