media:
  input: static/uploads
  output: /uploads

content:
  - name: poems
    label: Poems
    path: content/poems
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: poet
        label: Poet
        type: string
      - name: form
        label: Form (e.g. दोहा, पद, सवैया, कवित्त)
        type: select
        options:
          values: [दोहा, पद, सवैया, कवित्त, छंद, भजन, अन्य]
        required: false
      - name: themes
        label: Themes
        type: string
        list: true
      - name: audio_url
        label: Audio URL
        type: string
        required: false
      - name: notes
        label: Notes
        type: text
        required: false
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: date
        label: Date
        type: date
      - name: body
        label: Poem Text
        type: rich-text

  - name: poets
    label: Poets
    path: content/poets
    type: collection
    fields:
      - name: title
        label: Name
        type: string
        required: true
      - name: dates
        label: Dates (e.g. 1478–1583)
        type: string
        required: false
      - name: region
        label: Region
        type: string
        required: false
      - name: image
        label: Photo
        type: image
        required: false
      - name: date
        label: Date
        type: date
      - name: body
        label: Biography
        type: rich-text
