media:
  input: static/uploads
  output: /uploads

content:
  - name: poems
    label: Poems
    path: content/poems
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: poet
        label: Poet
        type: string
        - { label: "Poet name in English (e.g. Surdas)", name: "poet_en", widget: "string", required: false }
      - name: form
        label: Form (e.g. दोहा, पद, सवैया, कवित्त)
        type: select
        options:
          values: [दोहा, पद, सवैया, कवित्त, छंद, भजन, अन्य]
        required: false
      - name: themes
        label: Themes
        type: string
        list: true
      - name: audio_url
        label: Audio URL
        type: string
        required: false
      - name: notes
        label: Notes
        type: text
        required: false
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: date
        label: Date
        type: date
      - name: body
        label: Poem Text
        type: rich-text

  - name: poets
    label: Poets
    path: content/poets
    type: collection
    fields:
      - name: title
        label: Name
        type: string
        required: true
        - { label: "Name in English (e.g. Surdas)", name: "title_en", widget: "string", required: false }
      - name: dates
        label: Dates (e.g. 1478–1583)
        type: string
        required: false
      - name: region
        label: Region
        type: string
        required: false
      - name: image
        label: Photo
        type: image
        required: false
      - name: date
        label: Date
        type: date
      - name: body
        label: Biography
        type: rich-text

  - name: collections
    label: संग्रह / Collections
    path: content/collections
    type: collection
    fields:
    - name: title
      label: संग्रह का नाम / Collection Title
      type: string
    - name: description_hi
      label: विवरण (हिन्दी) / Description in Hindi
      type: string
      optional: true
    - name: description
      label: Description (English)
      type: string
      optional: true
    - name: poems
      label: कविताएँ / Poems (slugs)
      type: list
      hint: "Enter the filename of each poem without .md — e.g. surdas-madhura-milan"
    - name: draft
      label: Draft (hide from site)
      type: boolean
      default: false
    - name: date
      label: Date
      type: date